config/routes.rb
Rails.application.routes.draw do

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }


  # ユーザー用
  # URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #ゲストユーザー用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end


 root to: 'homes#top'



  namespace :admin do
    resources :foods, only: [:index, :show, :create] do
      resources :comments, only: [:create, :destroy]
    end
    resources :users, only: [:index, :show, :edit, :update]
  end



  scope module: "public" do
    get  "/users/sign_out" => "sessions#destroy" #ログアウト
    get "/users/my_page" => "users#show" #ユーザー情報詳細ページ（マイページ）表示
    get "/users/unsubscribe" => "users#unsubscribe" #退会確認画面の表示
    patch "/users/withdraw" => "users#withdraw" #退会フラグを切り替える

    resources :foods, only: [:index, :show, :create] do
      resources :comments, only: [:create, :destroy]
    end
    resources :users, only: [:edit, :update]
  end






  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :comments, dependent: :destroy
  # belongs_to :genre
  has_many :tagmaps, dependent: :destroy
  has_many :tags, through: :tagmaps

end

app/controllers/admin/foods_controller.rb
class Admin::FoodsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @foods = RakutenWebService::Ichiba::Item.search(:genreId => '100227')
    @arr = @foods.map {|food| food} #配列の形成

    if params[:search].present?
      # foods = food.items_serach(params[:search])

    elsif params[:tag_id].present?
      @tag = Tag.find(params[:tag_id])
      item_codes = Food.joins(:tags).where(tags: {id: params[:tag_id]}).pluck(:item_code)
      @arr = []
      item_codes.each do |item_code|
        @foods = RakutenWebService::Ichiba::Item.search(:itemCode => item_code)
        @foods.map{|food| food}.each do |f|
          @arr.append(f)
        end
      end

    elsif params[:keyword].present?
      @foods = RakutenWebService::Ichiba::Item.search(keyword: params[:keyword])
      @arr = @foods.map {|food| food} #配列の形成
    end

    @tag_lists = Tag.all
    @food_tags= params[:tag_id].present? ? Tag.find(params[:tag_id]).foods : Food.all
    @foods_page = Kaminari.paginate_array(@arr).page(params[:page]).per(10)

  end

  def show

    @food_detail = RakutenWebService::Ichiba::Item.search(itemCode: params[:id]).first
    @food = Food.new
    @comment = Comment.new
    @food_exist = Food.find_by(item_code: params[:id]) # Food ga create saretereba sono record wo syutoku !

    unless @food_exist.nil?
      @comments = Comment.where(food_id: @food_exist.id)
    end


  end

  def create
    @food = Food.new(food_params)
    @food.item_code = params[:item_code]
    @food.save
    redirect_to admin_food_path(params[:item_code])
  end

  private
  def food_params
      params.require(:food).permit(:name, :item_code, {tag_ids: []})
  end

end

app/helpers/admin/foods_helper.rb
module Admin::FoodsHelper
end

app/views/admin/foods/_comment_index.html.erb
<h3>コメント一覧</h3>
    <% comments.each do |comment| %>
      <div>
        投稿者：<%= comment.user.name %>
      </div>
      <div>
        <% if current_admin %>
        <%= check_box_tag :comment %>
        <% end %>
        <%= comment.impression %>
      </div>
        <h5 class="mb-3">評価：<%= comment.rate %>点 </h5>
        <div id="star-rate-<%= comment.id %>"></div>
          <script>
            $('#star-rate-<%= comment.id %>').raty({
            　size: 30,
              starOff:  '<%= asset_path('star-off.png') %>',
              starOn : '<%= asset_path('star-on.png') %>',
              starHalf: '<%= asset_path('star-half.png') %>',
              half: true,
              score: <%= comment.rate %>,
              readOnly: true
            });
          </script>
        <% if current_admin %>
        <div align="right">
          <%= link_to'コメントを削除', admin_food_comment_path(comment.food, comment), method: :delete, data: {confirm: '本当に削除してもよろしいですか？'}, class: "btn btn-danger" %>
        </div>
        <% end %>
    <% end %>

app/views/admin/foods/_food_name.html.erb
    <h2>品名</h2>
    <%= form_with model: food, url: foods_path(item_code: params[:id]), method: :post do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <div class="check_box">
      <span>タグ</span>
      <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :tag_name) do |tag| %>
        <div>
          <%= tag.label do %>
          <%= tag.check_box %>
          <%= tag.text %>
          <% end %>
        </div>
      <% end %>
    </div>
      <%= f.submit %>
    <% end %>

app/views/admin/foods/_search.html.erb
<%= form_tag admin_foods_path, method: :get do  %>
<%= text_field_tag 'keyword', params[:keyword], placeholder: 'キーワードで検索' %>
<%= submit_tag "検索" %>
<% end %>

app/views/admin/foods/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-11 col-sm-11 my-4">
    <h4 class="bg-light text-center col-md-4 col-sm-2 my-3">食品一覧</h4>
    <%= render 'search', foods: @foods %><br>
    <%= form_tag admin_foods_path, method: :get, class: 'boards__searchForm' do %>
      <%= select_tag :tag_id,
        options_from_collection_for_select(Tag.all, :id, :tag_name, params[:tag_id]),
        {
         prompt: 'タグで絞り込み検索',
         onchange: 'submit(this.form);'
        }
      %>
    <% end %>
    </div>

    <% @arr.each do |food| %>
      <% unless food["mediumImageUrls"].blank? %>
        <div class="col-md-3 col-sm-4 my-3">
          <%= link_to admin_food_path(food['itemCode']), class: 'text-dark' do %>
            <%= image_tag food["mediumImageUrls"][0], class: "food-image" %><br>
            <strong>
              <%= food.name.truncate(40) %>
            </strong><br>
            <%= render 'public/foods/rate_average', food: food %>
            <%= "#{ Comment.where(food_id: Food.where(item_code: food.code).pluck(:id)).count}コメント" %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="row offset-5">
    <%= paginate @foods_page %>
  </div>
</div>

app/views/admin/foods/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h3>食品概要</h3>
      <%= image_tag @food_detail["mediumImageUrls"][0], class: "food-image" %><br>
    </div>
    <div class="col-md-9">
      <%= @food_detail['itemCaption'] %>
    </div>
  </div>

  <% if @food_exist.nil? %>
    <%= render 'food_name', food: @food %>
  <% else %>
    <h4>品名</h4>
    <h5><%= @food_exist.name %></h5><br>
    <%= render 'comment_index', comments: @comments %>
  <% end %>
</div>