config/routes.rb
Rails.application.routes.draw do

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }


  # ユーザー用
  # URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #ゲストユーザー用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end


 root to: 'homes#top'



  namespace :admin do
    resources :foods, only: [:index, :show, :create] do
      resources :comments, only: [:create, :destroy]
    end
    resources :users, only: [:index, :show, :edit, :update]
  end



  scope module: "public" do
    get  "/users/sign_out" => "sessions#destroy" #ログアウト
    get "/users/my_page" => "users#show" #ユーザー情報詳細ページ（マイページ）表示
    get "/users/unsubscribe" => "users#unsubscribe" #退会確認画面の表示
    patch "/users/withdraw" => "users#withdraw" #退会フラグを切り替える

    resources :foods, only: [:index, :show, :create] do
      resources :comments, only: [:create, :destroy]
    end
    resources :users, only: [:edit, :update]
  end






  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :check
  def top
  end

  def check
    if user_signed_in?
      redirect_to foods_path
      flash[:notice] = "トップページに戻る場合は、ログアウトしてください。"
    end
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/top.html.erb
<div class="jumbotron text-center hero">
  <div class="container">
    <div class="row">
      <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
        <div class="line anim js-anim3"><h1>ようこそ <strong>FoodsView</strong>へ!!</h1></div>
        <p>FoodsViewは食品専用のレビューサイトです！</p>

        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, class: "btn btn-secondary btn-sm btn-block mb-3 sign_in", method: :post %>
          </div>

          <div class="row">
            <%= link_to 'ログイン',new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
          </div>

          <div class="row">
            <%= link_to '新規登録',new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(function(){
    var $target3 = $('.js-anim3');

    var anim3 = function() {
      if(($target3).hasClass('is-animated')){
        $target3.removeClass('is-animated');
        // setTimeout(anim3, 3000)
      } else {
        $target3.addClass('is-animated');
        // setTimeout(anim3, 3000)
      }
    }
    anim3();
  })
  </script>