config/routes.rb
Rails.application.routes.draw do

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }


  # ユーザー用
  # URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #ゲストユーザー用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end


 root to: 'homes#top'



  namespace :admin do
    resources :foods, only: [:index, :show, :create] do
      resources :comments, only: [:create, :destroy]
    end
    resources :users, only: [:index, :show, :edit, :update]
  end



  scope module: "public" do
    get  "/users/sign_out" => "sessions#destroy" #ログアウト
    get "/users/my_page" => "users#show" #ユーザー情報詳細ページ（マイページ）表示
    get "/users/unsubscribe" => "users#unsubscribe" #退会確認画面の表示
    patch "/users/withdraw" => "users#withdraw" #退会フラグを切り替える

    resources :foods, only: [:index, :show, :create] do
      resources :comments, only: [:create, :destroy]
    end
    resources :users, only: [:edit, :update]
  end






  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :comments, dependent: :destroy


  def get_profile_image(width,height) #モデルに記述することでhtmlファイルにおいて　.get_profile_image というメソッド形式で呼び出せる。
    unless profile_image.attached? #プロフィール画像が存在しない場合
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io:File.open(file_path), filename:'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end


  def self.guest
    find_or_create_by!(name: 'ゲストユーザー' ,email: 'guest@example.com') do |user| #find_or_create_by(条件)  条件としたデータの検索と作成を自動的に判断して処理を行うメソッド
      user.password = SecureRandom.urlsafe_base64  #SecureRandom.urlsafe_base64  ランダムな文字列を生成するメソッド
      user.name = "ゲストユーザー"
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.page(params[:page]).per(10)
  end

  def show
    @user =User.find(params[:id])
  end

  def edit
    @user =User.find(params[:id])
  end

  def update
   @user =User.find(params[:id])
   if @user.update(user_params)
    flash[:notice] = "更新が完了しました。"
    redirect_to admin_user_path(@user.id)
   end
  end


  private
  def user_params
    params.require(:user).permit(:name, :email, :withdraw, :is_deleted, )
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-4 mt-3 mb-4 offset-3">
      <h4 class="bg-light text-center mt-3"><%= @user.name %>さんのユーザー情報</h4>
    </div>
  </div>

  <div class="row">
    <div class="col-11 mt-3 offset-4">
      <%= form_with model: @user, url: admin_user_path, local: true do |f| %>
       <form>
         <div class="form-group">
           <%= f.label :id, "ユーザーID" %>
           <%= @user.id %><br>
           <%= f.label :name, "ニックネーム" %>
           <strong><%= @user.name %></strong><br>

           <%= f.label :メールアドレス  %>
           <strong><%= @user.email %></strong><br>

           <%= f.label :ユーザーステータス %><br>
           <%= f.radio_button :is_deleted, false %>
           <%= f.label :ユーザーステータス, "有効", value: false %>
           <%= f.radio_button :is_deleted, true %>
           <%= f.label :ユーザーステータス, "退会", value: true %><br>

           <%= f.submit "変更を保存", class: "btn btn-success offset-3" %>
         </div>
       </form>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="conteiner">
  <div class="row">
    <div class="col-2 offset-2">
      <h5 class="bg-light text-center my-5 ml-4">ユーザー一覧</h5>
    </div>
  </div>

  <div class="row">
    <div class="col-7 mx-auto">
      <table class="table">
        <thead>
          <tr class="bg-light">
            <th>ユーザーID</th>
            <th>ニックネーム</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
           <tr>
             <td><%= user.id %></td>
             <td>
               <%= link_to admin_user_path(user), class: "text-blue" do %>
                <% user.name %>
               <% end %>
             </td>
             <td>
               <%= user.email %>
             </td>
             <td>
               <%if user.is_deleted == false %>
                <span class="text-success font-weight-bold">有効ユーザー</span>
               <% else %>
                <span class="text-secondar font-weght-bold">退会</span>
               <% end %>
             </td>
           </tr>
          <% end %>
        </tbody>
      </table>
      <div class="col offset-5"><%= paginate @users %></div>
    </div>
  </div>

</div>

app/views/admin/users/show.html.erb
<div class= "container">
  <div class="row">
    <div class="col-4 mb-5 offset-1">
      <h5 class="bg-light text-center mt-3"><%= @user.name %>さんの<br>
      ユーザー情報</h5>
    </div>
  </div>

  <div class="row">
    <div class="col-8 mb-2 mx-auto">
      <table class="table">
        <tr>
          <th>ユーザーID</th>
          <th><%= @user.id %></th>
        </tr>
        <tr>
          <th>ニックネーム</th>
          <th><%= @user.name %></th>
        </tr>
        <tr>
          <th>ユーザーステータス</th>
          <th>
            <% if @user.is_deleted == false %>
             <p class="text-success">有効</p>
            <% else %>
             <p class="text-secondary">退会</p>
            <% end %>
          </th>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-4 offset-7">
      <tr class="text-center">
        <th><%= link_to "編集", edit_admin_user_path, class: "btn btn-success" %></th>
      </tr>
    </div>
  </div>

</div>