config/routes.rb
Rails.application.routes.draw do

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }


  # ユーザー用
  # URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #ゲストユーザー用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end


 root to: 'homes#top'



  namespace :admin do
    resources :foods, only: [:index, :show, :create] do
      resources :comments, only: [:create, :destroy]
    end
    resources :users, only: [:index, :show, :edit, :update]
  end



  scope module: "public" do
    get  "/users/sign_out" => "sessions#destroy" #ログアウト
    get "/users/my_page" => "users#show" #ユーザー情報詳細ページ（マイページ）表示
    get "/users/unsubscribe" => "users#unsubscribe" #退会確認画面の表示
    patch "/users/withdraw" => "users#withdraw" #退会フラグを切り替える

    resources :foods, only: [:index, :show, :create] do
      resources :comments, only: [:create, :destroy]
    end
    resources :users, only: [:edit, :update]
  end






  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
 belongs_to :user
 belongs_to :admin, optional: true
 belongs_to :food
 validates :impression, presence: true
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :comments, dependent: :destroy
  # belongs_to :genre
  has_many :tagmaps, dependent: :destroy
  has_many :tags, through: :tagmaps

end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tagmaps, dependent: :destroy
  has_many :foods, through: :tagmaps
end

app/models/tagmap.rb
class Tagmap < ApplicationRecord
  belongs_to :food
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :comments, dependent: :destroy


  def get_profile_image(width,height) #モデルに記述することでhtmlファイルにおいて　.get_profile_image というメソッド形式で呼び出せる。
    unless profile_image.attached? #プロフィール画像が存在しない場合
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io:File.open(file_path), filename:'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end


  def self.guest
    find_or_create_by!(name: 'ゲストユーザー' ,email: 'guest@example.com') do |user| #find_or_create_by(条件)  条件としたデータの検索と作成を自動的に判断して処理を行うメソッド
      user.password = SecureRandom.urlsafe_base64  #SecureRandom.urlsafe_base64  ランダムな文字列を生成するメソッド
      user.name = "ゲストユーザー"
    end
  end

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController

  def create
    # food = Food.find(params[:food_id])
    # comment = Comment.new(comment_params)
    # #comment.admin_id = current_admin.id
    # comment.food_id = params[:food_id]
    # comment.save
    # redirect_to admin_food_path(food.item_code)
  end

  def destroy
    # Comment.find_by(id: params[:id], food_id: params[:food_id]).destroy
    Comment.find(params[:id]).destroy
    redirect_to request.referer #同じページに遷移する
  end

  private
  def comment_params
    params.require(:comment).permit(:id, :impression, :rate)
  end

end

app/controllers/admin/foods_controller.rb
class Admin::FoodsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @foods = RakutenWebService::Ichiba::Item.search(:genreId => '100227')
    @arr = @foods.map {|food| food} #配列の形成

    if params[:search].present?
      # foods = food.items_serach(params[:search])

    elsif params[:tag_id].present?
      @tag = Tag.find(params[:tag_id])
      item_codes = Food.joins(:tags).where(tags: {id: params[:tag_id]}).pluck(:item_code)
      @arr = []
      item_codes.each do |item_code|
        @foods = RakutenWebService::Ichiba::Item.search(:itemCode => item_code)
        @foods.map{|food| food}.each do |f|
          @arr.append(f)
        end
      end

    elsif params[:keyword].present?
      @foods = RakutenWebService::Ichiba::Item.search(keyword: params[:keyword])
      @arr = @foods.map {|food| food} #配列の形成
    end

    @tag_lists = Tag.all
    @food_tags= params[:tag_id].present? ? Tag.find(params[:tag_id]).foods : Food.all
    @foods_page = Kaminari.paginate_array(@arr).page(params[:page]).per(10)

  end

  def show

    @food_detail = RakutenWebService::Ichiba::Item.search(itemCode: params[:id]).first
    @food = Food.new
    @comment = Comment.new
    @food_exist = Food.find_by(item_code: params[:id]) # Food ga create saretereba sono record wo syutoku !

    unless @food_exist.nil?
      @comments = Comment.where(food_id: @food_exist.id)
    end


  end

  def create
    @food = Food.new(food_params)
    @food.item_code = params[:item_code]
    @food.save
    redirect_to admin_food_path(params[:item_code])
  end

  private
  def food_params
      params.require(:food).permit(:name, :item_code, {tag_ids: []})
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.page(params[:page]).per(10)
  end

  def show
    @user =User.find(params[:id])
  end

  def edit
    @user =User.find(params[:id])
  end

  def update
   @user =User.find(params[:id])
   if @user.update(user_params)
    flash[:notice] = "更新が完了しました。"
    redirect_to admin_user_path(@user.id)
   end
  end


  private
  def user_params
    params.require(:user).permit(:name, :email, :withdraw, :is_deleted, )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_up_path_for(resource)
    flash[:notice] = '新規登録が完了しました。'
    foods_path
  end

  def after_sign_in_path_for(resource)
    flash[:notice] = 'ログインしました。'
    foods_path
  end
  # def after_sign_in_path_for(resource_or_scope)
  #   stored_location_for(resource_or_scope) || signed_in_root_path(resource_or_scope)
  # end


  def after_sign_out_path_for(resource)
    flash[:notice] = 'ログアウトしました。'
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile_image]) #sign_up時にnameとプロフィール画像のデータ操作を許可している。
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :check
  def top
  end

  def check
    if user_signed_in?
      redirect_to foods_path
      flash[:notice] = "トップページに戻る場合は、ログアウトしてください。"
    end
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/foods_helper.rb
module Admin::FoodsHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def score_average(food)
    fd = Food.find_by(item_code:  food['itemCode'] )
    if fd
      score = fd.comments.average(:rate)
    else
      score = 0
    end
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%#- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%#= link_to "Sign up", new_registration_path(resource_name) %><br />
<%# end %>

<%#- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%#= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<%# end %>

<%#- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%#= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<%# end %>

<%#- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%#= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<%# end %>

<%#- if devise_mapping.omniauthable? %>
  <%#- resource_class.omniauth_providers.each do |provider| %>
    <%#= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <%# end %>
<%# end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodsView</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> <!-- app/javascript 配下のファイルを参照するようになる。-->
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/dd1e8a5a25.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark ">
        <div class="container">
          <div class="kiran">
            <a class="navbar-brand" href="/"><span>FoodsView</span></a>
          </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div button class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
            <!--管理者ログイン後のヘッダー-->
                <% if admin_signed_in? && request.url.include?('/admin') %>
                <li>
                  <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-light' do %>
                   <i class="fas fa-sign-out-alt"></i>ログアウト
                  <% end %>
                </li>
                <li>
                  <%= link_to admin_users_path, class: 'nav-link text-light' do %>
                   <i class="fas fa-users"></i> ユーザー一覧
                  <% end %>
                </li>
                <li>
                  <%= link_to admin_foods_path, class: 'nav-link text-light' do %>
                   <i class="fa-solid fa-bowl-food"></i>食品一覧
                  <% end %>
                </li>
        <!--ユーザーログイン後のヘッダー-->
                <% elsif user_signed_in? %>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                   <i class="fas fa-sign-out-alt"></i> ログアウト
                  <% end %>
                </li>
                <li>
                  <%= link_to users_my_page_path, class: 'nav-link text-light' do %>
                   <i class="fa-solid fa-user"></i>マイページ
                  <% end %>
                </li>
                <li>
                  <%= link_to foods_path, class: 'nav-link text-light' do %>
                   <i class="fa-solid fa-bowl-food"></i>食品一覧
                  <% end %>
                </li>
                <% end %>
              </ul>
            </div>
        </div>
      </header>

      <main>
        <!--<p id="notice"><%#= notice %></p>-->
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key}") %>
        <% end %>    
      </main>

      <%= yield %>

      <footer>
        <div class="container mt-5">
          <div class="row">
            <div class="mx-auto">
              <p>CopyRight 2022</p>
            </div>
          </div>
        </div>
      </footer>
  </body>
</html>